Version: 0.2 

phases:
  install:    
    runtime-version:
      java: openjdk8 
    #commands:
    #  - echo nothing to do in the install phase.
    pre_build:
      commands:  
        - echo nothing to do in the pre_build phase.
    build:
      commands: 
        - echo Build started on `date`
        - mvn install 
    #    - mvn package
    post_build: 
      commands:
        - echo Build Completed on `data`
    artifacts: 
      files:
        - target/demo.zip          
